#!/usr/bin/perl

$TEST_DESCRIPTION = "searchStrategy='hsvi' for pomdp, mdp";
require "testLibrary.perl";
&testZmdpBenchmark(cmd => "$zmdpBenchmark --searchStrategy hsvi $pomdpsDir/three_state.pomdp",
		   expectedLB => 20.8261,
		   expectedUB => 20.8271,
		   testTolerance => 0.01,
		   outFiles => ["bounds.plot", "inc.plot", "sim.plot"]);
&testZmdpBenchmark(cmd => "$zmdpBenchmark --searchStrategy hsvi $mdpsDir/small-b.racetrack",
		   expectedLB => -13.2664,
		   expectedUB => -13.2655,
		   testTolerance => 0.01,
		   outFiles => ["bounds.plot", "inc.plot", "sim.plot"]);
