/********** tell emacs we use -*- c++ -*- style comments *******************
 $Revision: 1.1 $  $Author: trey $  $Date: 2006-06-24 16:25:27 $
   
 @file    PomdpExec.cc
 @brief   No brief

 Copyright (c) 2002-2006, Trey Smith. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License"); you may
 not use this file except in compliance with the License.  You may
 obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 implied.  See the License for the specific language governing
 permissions and limitations under the License.

 ***************************************************************************/

/***************************************************************************
 * INCLUDES
 ***************************************************************************/

//#include <assert.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <assert.h>
#include <sys/time.h>

#include <iostream>
#include <fstream>

#include "zmdpCommonDefs.h"
#include "MatrixUtils.h"
#include "PomdpExec.h"

using namespace std;
using namespace MatrixUtils;
using namespace sla;

namespace zmdp {

PomdpExec::PomdpExec(void) :
  pomdp(NULL),
  policy(NULL),
  currentBeliefInitialized(false)
{}

// read in the pomdp model and the policy generated by zmdpSolve
void PomdpExec::init(const std::string& modelFileName,
		     bool useFastParser,
		     const std::string& policyFileName)
{
  timeval tv1, tv2;

  printf("PomdpExec: reading pomdp model, useFastParser=%d\n",
	 useFastParser);
  gettimeofday(&tv1, NULL);
  pomdp = new Pomdp(modelFileName, useFastParser);
  gettimeofday(&tv2, NULL);
  printf("  (took %.3f seconds)\n",
	 (tv2.tv_sec - tv1.tv_sec) + 1e-6*(tv2.tv_usec - tv1.tv_usec));

  policy = new MaxPlanesLowerBound(pomdp);

  printf("PomdpExec: reading policy\n");
  gettimeofday(&tv1, NULL);
  policy->readFromFile(policyFileName);
  gettimeofday(&tv2, NULL);
  printf("  (took %.3f seconds)\n",
	 (tv2.tv_sec - tv1.tv_sec) + 1e-6*(tv2.tv_usec - tv1.tv_usec));

  currentBeliefInitialized = false;
}

void PomdpExec::setToInitialBelief(void)
{
  currentBelief = pomdp->getInitialBelief();
  currentBeliefInitialized = true;
}

int PomdpExec::chooseAction(void)
{
  return policy->getBestLBPlane(currentBelief).action;
}

void PomdpExec::advanceToNextBelief(int a, int o)
{
  pomdp->getNextBelief(currentBelief, currentBelief, a, o);
}

bool PomdpExec::getBeliefIsTerminal(void)
{
  return pomdp->getIsTerminalState(currentBelief);
}

void PomdpExec::setBelief(const belief_vector& b)
{
  currentBelief = b;
}
 
belief_vector& PomdpExec::getBelief(belief_vector& b)
{
  b = currentBelief;
  return b;
}

int PomdpExec::getRandomObservation(int a)
{
  obs_prob_vector opv;
  return chooseFromDistribution(pomdp->getObsProbVector(opv, currentBelief, a));
}

}; // namespace zmdp

/***************************************************************************
 * REVISION HISTORY:
 * $Log: not supported by cvs2svn $
 *
 ***************************************************************************/
