#!/usr/bin/perl

$TEST_DESCRIPTION = "default use of zmdpBenchmark on an mdp";
require "testLibrary.perl";
&testZmdpBenchmark(cmd => "$zmdpBenchmark $mdpsDir/small-b.racetrack",
		   expectedLB => -13.2664,
		   expectedUB => -13.2654,
		   testTolerance => 0.01,
		   outFiles => ["bounds.plot", "inc.plot", "sim.plot"]);
