#!/usr/bin/perl

$TEST_DESCRIPTION = "zmdpEvaluate with distinct models";
require "testLibrary.perl";

# (test both normal and fast parser)
&testZmdpBenchmark(cmd => "$zmdpBenchmark -o out.policy ../test13.pomdp",
		   expectedLB => 20.8260,
		   expectedUB => 20.8269,
		   testTolerance => 0.01,
		   outFiles => ["bounds.plot", "inc.plot", "sim.plot"]);
&testZmdpEvaluate(cmd => "$zmdpEvaluate -p out.policy -m $pomdpsDir/term3.pomdp ../test13.pomdp",
		  expectedMean => 20.826,
		  testTolerance => 1.0,
		  outFiles => ["scores.plot", "sim.plot"]);
