#!/usr/bin/perl

$TEST_DESCRIPTION = "read pomdp model with fast parser";
require "testLibrary.perl";
&testZmdpBenchmark(cmd => "$zmdpBenchmark -f $pomdpsDir/term3_strict.pomdp",
		   expectedUB => 10.5882,
		   testTolerance => 0.01,
		   outFiles => ["bounds.plot", "inc.plot", "sim.plot"]);
