#!/usr/bin/perl

$TEST_DESCRIPTION = "searchStrategy='hdp' for pomdp, mdp";
require "testLibrary.perl";
&testZmdpBenchmark(cmd => "$zmdpBenchmark --searchStrategy hdp $pomdpsDir/term3.pomdp",
		   expectedUB => 10.5882,
		   testTolerance => 0.01,
		   outFiles => ["bounds.plot", "inc.plot", "sim.plot"]);
&testZmdpBenchmark(cmd => "$zmdpBenchmark --searchStrategy hdp $mdpsDir/small-b.racetrack",
		   expectedUB => -13.2655,
		   testTolerance => 0.01,
		   outFiles => ["bounds.plot", "inc.plot", "sim.plot"]);
