#!/usr/bin/perl -w

$num = 0;
while (<>) {
    if (/upperBoundInternal: val1=(.*) val3=(.*)/) {
	$val1 = $1;
	$val3 = $2;

	if ($val3 < $val1) {
	    print $_;
	}
	$num++;
    }
}
print "processed $num entries\n";
