#!/bin/sh

# steps:
#  options.mak: update ZMDP_VERSION
#  README: update release notes
#   - use 'cvs diff -r zmdp-old-version -D now'
#   - include svn revision number
#  repository: commit above changes
#  make version directory and tarball 'makepackage x.x.x'
#  test build and functionality in version directory
#  copy tarball and README to www directory
#  update www/zmdp/index.html

VERSION=$1
if [ -z $VERSION ]; then
  echo 'ERROR: specify version'
  exit 1
fi
mkdir zmdp-$VERSION
cd zmdp-$VERSION
zmdp
svn export file:///home/trey/projects/zmdp/svnRepository/src
mv src/{README,COPYING} .
rm -rf src/pomdpModels/RockExplore
cd ..
echo 'building tarball'
tar cfz zmdp-${VERSION}.tgz zmdp-$VERSION
echo 'done'
