#!/bin/sh

# steps:
#  options.mak: update ZMDP_VERSION
#  README: update release notes (use 'cvs diff -r zmdp-old-version -D now')
#  README: update installation instructions to show correct version
#  repository: 'cvs rtag zmdp-x-x-x src'
#  make version directory and tarball 'makepackage x.x.x'
#  test build and functionality in version directory
#  copy tarball and README to www directory
#  update www/zmdp/index.html

VERSION=$1
if [ -z $VERSION ]; then
  echo 'ERROR: specify version'
  exit 1
fi
mkdir zmdp-$VERSION
cd zmdp-$VERSION
zmdp
cvs checkout src
mv src/{README,COPYING} .
cd ..
echo 'building tarball'
tar cfz zmdp-${VERSION}.tgz zmdp-$VERSION
echo 'done'
