name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build . -f ./src/docker/Dockerfile -t trey0/zmdp:latest

    - name: Test
      run: docker build . -f ./src/docker/Dockerfile_test -t test
