#!/usr/bin/perl -w

sub usage {
    die  "usage: compareplots OPTIONS <dir1> <dir2>\n"
	."   -h    Print this help\n"
	."   -t    Plot bounds vs. time\n"
        ."   -i    Plot bounds vs. number of top-level iterations\n"
	."   -s    Plot speed (iterations v. time)\n"
	."   -q    Plot policy quality v. time\n"
        ."   -p    Generate postscript output\n";
}

my $dir1;
my $dir2;
my $postscript_output = 0;
my @plot_types = ();
for (@ARGV) {
    if (/^-/) {
	if ($_ eq "-h" or $_ eq "--help") {
	    &usage;
	} elsif ($_ eq "-p") {
	    $postscript_output = 1;
	} elsif ($_ eq "-t") {
	    push @plot_types, 't';
	} elsif ($_ eq "-i") {
	    push @plot_types, 'i';
	} elsif ($_ eq "-s") {
	    push @plot_types, 's';
	} elsif ($_ eq "-q") {
	    push @plot_types, 'q';
	} else {
	    print STDERR "ERROR: unknown option $_\n\n";
	    &usage;
	}
    } else {
	if (!defined $dir1) {
	    $dir1 = $_;
	} elsif (!defined $dir2) {
	    $dir2 = $_;
	} else {
	    print STDERR "ERROR: too many arguments\n\n";
	    &usage;
	}
    }
}
if (!defined $dir1 or !defined $dir2) {
    print STDERR "ERROR: not enough arguments\n\n";
    &usage;
}
if ($#plot_types == -1) {
    @plot_types = 't';
}

for (@plot_types) {
    &do_plot($dir1, $dir2, $_, $postscript_output);
}

sub do_plot {
    my $dir1 = shift;
    my $dir2 = shift;
    my $plot_type = shift;
    my $postscript_output = shift;

    # remove trailing slash
    $dir1 =~ s:/$::;
    $dir2 =~ s:/$::;

    my $options = "";
    if ($postscript_output) {
	$options = "> ${dir1}_${dir2}_compare.ps";
    } else {
	$options = "-persist";
    }
    
    my $bounds1_file = "${dir1}/bounds.plot";
    my $bounds2_file = "${dir2}/bounds.plot";

    my $inc1_file = "${dir1}/inc.plot";
    my $inc2_file = "${dir2}/inc.plot";

    open(GP, "|gnuplot $options") or die "couldn't run gnuplot: $!\n";
    select GP;
    $| = 1;
    select STDOUT;
    
    if ($postscript_output) {
	print GP "set terminal postscript\n";
    }

if ($plot_type eq 'i') {

print GP <<"EOF";

######################################################################
set logscale x
set xlabel "number of top-level iterations"
set ylabel "solution quality"
set title "$dir1 vs. $dir2"
plot "$bounds1_file" using 0:3    title "upper bound $dir1" with lines,     \\\
     "$bounds1_file" using 0:2    title "lower bound $dir1" with lines,     \\\
     "$bounds2_file" using 0:3    title "upper bound $dir2" with lines,     \\\
     "$bounds2_file" using 0:2    title "lower bound $dir2" with lines
     
######################################################################

EOF

} elsif ($plot_type eq 's') {

print GP <<"EOF";

######################################################################
set logscale x
set logscale y
set xlabel "wallclock time (seconds)"
#set ylabel "number of top-level iterations"
set title "$dir1 vs. $dir2"
plot "$bounds1_file" using 1:6    title "$dir1 # top level iterations" with lines,     \\\
     "$bounds2_file" using 1:6    title "$dir2 # top level iterations" with lines,     \\\
     "$bounds1_file" using 1:7    title "$dir1 # backups"              with lines,     \\\
     "$bounds2_file" using 1:7    title "$dir2 # backups"              with lines,     \\\
     "$bounds1_file" using 1:9    title "$dir1 # belief comparisons"   with lines,     \\\
     "$bounds2_file" using 1:9    title "$dir2 # belief comparisons"   with lines
     
######################################################################

EOF

} elsif ($plot_type eq 'q') {

print GP <<"EOF";

######################################################################
set logscale x
set xlabel "wallclock time (seconds)"
set title "$dir1 vs. $dir2"
plot "$inc1_file" using 1:2     title "$dir1" with lines, \\\
     "$inc1_file" using 1:2:3:4 notitle with errorbars,   \\\
     "$inc2_file" using 1:2     title "$dir2" with lines, \\\
     "$inc2_file" using 1:2:3:4 notitle with errorbars
     
######################################################################

EOF

} else { # plot_type eq 't'

print GP <<"EOF";

######################################################################
set logscale x
set xlabel "wallclock time (seconds)"
set ylabel "solution quality"
set title "$dir1 vs. $dir2"
plot \\\
     "$bounds1_file" using 1:3    title "upper bound $dir1" with lines,     \\\
     "$bounds1_file" using 1:2    title "lower bound $dir1" with lines,     \\\
     "$bounds2_file" using 1:3    title "upper bound $dir2" with lines,     \\\
     "$bounds2_file" using 1:2    title "lower bound $dir2" with lines
     
#     "$inc1_file"    using 1:2    title "simulation $dir1"  with lines,     \\\
#     "$inc1_file"    using 1:2:3  notitle                   with errorbars, \\\
#     "$inc2_file"    using 1:2    title "simulation $dir2"  with lines,     \\\
#     "$inc2_file"    using 1:2:3  notitle                   with errorbars

######################################################################

EOF

}

} # end sub

